import type { DemoState } from "@/lib/demo-types";
import { defaultModelSettings } from "@/lib/model-settings";

export const memberNavigation = [
  { href: "/member", label: "首页", description: "本周安排与重点" },
  { href: "/member/assistant", label: "AI 助理", description: "获取训练与恢复建议" },
  { href: "/member/plan", label: "我的计划", description: "查看本周计划并打卡" },
  { href: "/member/guidance", label: "动作指导", description: "查看动作要点与提醒" },
  { href: "/member/review", label: "复盘", description: "提交反馈并跟进调整" },
];

export const coachNavigation = [
  { href: "/coach", label: "教练首页", description: "待处理会员概览" },
  { href: "/coach/plans", label: "计划列表", description: "筛选、分页与计划详情" },
  { href: "/coach/reviews", label: "复盘列表", description: "筛选、分页与复盘详情" },
];

export const adminNavigation = [
  { href: "/admin", label: "后台首页", description: "系统配置概览" },
  { href: "/admin/knowledge-base", label: "知识库", description: "筛选、分页与详情" },
  { href: "/admin/model-settings", label: "模型配置", description: "Prompt 与模型策略" },
  { href: "/admin/members", label: "会员数据", description: "多会员列表与筛选" },
];

const now = "2026-04-17T09:00:00.000Z";

export const initialDemoState: DemoState = {
  session: {
    isAuthenticated: false,
    userId: null,
    username: null,
    role: null,
    displayName: null,
    memberId: null,
    coachId: null,
    locationName: null,
  },
  currentRole: "member",
  memberProfile: {
    id: "member-chen",
    memberName: "陈奕辰",
    coachName: "教练 李安",
    coachId: "coach-li",
    locationName: "PulseLab 徐汇店",
    age: 28,
    sex: "男",
    heightCm: 178,
    weightKg: 75,
    goalLabel: "8 周减脂与基础力量提升",
    goalWindow: "2026-04-01 至 2026-05-27",
    trainingDays: 4,
    sessionMinutes: 45,
    equipmentAccess: "健身房",
    trainingLevel: "进阶",
    injuryHistory: "右膝偶发不适，无明确诊断。",
    dietPreference: "高蛋白、正常碳水",
    wearablePermissionStatus: "待接入",
    lastCoachEditReason: "因右膝反馈不适，教练下调了下肢训练容量并替换冲击动作。",
    planVersion: 3,
    updatedAt: now,
  },
  weeklyPlan: {
    memberId: "member-chen",
    version: 3,
    days: [
      {
        id: "member-chen-day-1",
        memberId: "member-chen",
        dayLabel: "Day 1",
        focus: "上肢推拉 + 核心",
        duration: "45 分钟",
        intensity: "RPE 7",
        completed: true,
        coachNote: "维持动作质量，卧推动作不过度追求负重。",
      },
      {
        id: "member-chen-day-2",
        memberId: "member-chen",
        dayLabel: "Day 2",
        focus: "下肢稳定 + 低冲击有氧",
        duration: "45 分钟",
        intensity: "RPE 6-7",
        completed: true,
        coachNote: "避开跳跃动作，优先稳定控制。",
      },
      {
        id: "member-chen-day-3",
        memberId: "member-chen",
        dayLabel: "Day 3",
        focus: "上肢力量 + 后链",
        duration: "45 分钟",
        intensity: "RPE 7",
        completed: true,
        coachNote: "罗马尼亚硬拉保持脊柱中立。",
      },
      {
        id: "member-chen-day-4",
        memberId: "member-chen",
        dayLabel: "Day 4",
        focus: "全身代谢循环",
        duration: "45 分钟",
        intensity: "RPE 7-8",
        completed: false,
        coachNote: "训练后追加 12 分钟自行车。",
      },
    ],
  },
  coachEdits: [
    {
      id: "edit-1",
      memberId: "member-chen",
      dayId: "member-chen-day-2",
      exercise: "Day 2",
      editor: "教练 李安",
      aiVersion: "下肢力量强化 · RPE 8 · 原计划含冲击动作",
      coachVersion: "下肢稳定 + 低冲击有氧 · RPE 6-7 · 避开跳跃动作，优先稳定控制。",
      reason: "会员近期反馈右膝不适，先降低轴向负荷并加强动作控制。",
      createdAt: "2026-04-15T19:20:00.000Z",
    },
    {
      id: "edit-2",
      memberId: "member-chen",
      dayId: "member-chen-day-4",
      exercise: "Day 4",
      editor: "教练 李安",
      aiVersion: "全身爆发循环 · RPE 8 · 波比跳 3 组 x 12 次",
      coachVersion: "全身代谢循环 · RPE 7-8 · 训练后追加 12 分钟自行车。",
      reason: "为了控制冲击，改成更适合当前状态的低冲击有氧。",
      createdAt: "2026-04-15T19:32:00.000Z",
    },
  ],
  knowledgeBase: [
    {
      id: "kb-motion",
      name: "动作规范",
      description: "高频动作的目标肌群、动作要点、常见错误、替代动作。",
      documents: 18,
      enabled: true,
      category: "训练动作",
      updatedAt: now,
    },
    {
      id: "kb-safety",
      name: "安全注意事项",
      description: "疼痛、眩晕、伤病史、停止训练边界与升级提示。",
      documents: 9,
      enabled: true,
      category: "风险边界",
      updatedAt: now,
    },
    {
      id: "kb-nutrition",
      name: "营养常识",
      description: "第一版用于轻量建议与引用，不做复杂饮食 Agent。",
      documents: 6,
      enabled: true,
      category: "营养",
      updatedAt: now,
    },
    {
      id: "kb-recovery",
      name: "恢复策略",
      description: "睡眠、拉伸、训练后恢复与主观疲劳判断。",
      documents: 11,
      enabled: true,
      category: "恢复",
      updatedAt: now,
    },
    {
      id: "kb-beginner",
      name: "新手训练原则",
      description: "新手常见错误、动作进阶逻辑与负荷控制。",
      documents: 14,
      enabled: false,
      category: "训练原则",
      updatedAt: now,
    },
  ],
  modelSettings: defaultModelSettings(),
  coachQueue: [
    {
      id: "queue-1",
      memberId: "member-chen",
      member: "陈奕辰",
      location: "徐汇店",
      task: "复核 v3 计划变更",
      owner: "教练 李安",
      status: "待确认",
      createdAt: now,
    },
    {
      id: "queue-2",
      memberId: "member-zhou",
      member: "周可心",
      location: "静安店",
      task: "查看动作指导风险提醒",
      owner: "教练 王洁",
      status: "高优先级",
      createdAt: now,
    },
    {
      id: "queue-3",
      memberId: "member-song",
      member: "宋一帆",
      location: "浦东店",
      task: "追踪 2 周减脂复盘",
      owner: "教练 林策",
      status: "处理中",
      createdAt: now,
    },
  ],
  usersByCoach: [
    { coach: "教练 李安", location: "徐汇店", members: 4 },
    { coach: "教练 王洁", location: "静安店", members: 3 },
    { coach: "教练 林策", location: "浦东店", members: 3 },
  ],
  review: {
    id: "review-chen-1",
    memberId: "member-chen",
    memberName: "陈奕辰",
    coachName: "教练 李安",
    locationName: "PulseLab 徐汇店",
    completedSessions: 3,
    totalSessions: 4,
    fatigueScore: 6,
    weightChangeKg: -0.6,
    note: "Day 4 因出差未完成，右膝偶尔不适。",
    riskLevel: "watch",
    nextAdjustment: "下肢训练采用更稳妥的动作替代，避免风险累积。",
    createdAt: now,
  },
  members: [
    {
      id: "member-chen",
      memberName: "陈奕辰",
      coachName: "教练 李安",
      coachId: "coach-li",
      locationName: "PulseLab 徐汇店",
      goalLabel: "8 周减脂与基础力量提升",
      trainingLevel: "进阶",
      planVersion: 3,
      latestReviewRisk: "watch",
      updatedAt: now,
    },
    {
      id: "member-zhou",
      memberName: "周可心",
      coachName: "教练 王洁",
      coachId: "coach-wang",
      locationName: "PulseLab 静安店",
      goalLabel: "改善体态与核心稳定",
      trainingLevel: "新手",
      planVersion: 2,
      latestReviewRisk: "normal",
      updatedAt: now,
    },
    {
      id: "member-song",
      memberName: "宋一帆",
      coachName: "教练 林策",
      coachId: "coach-lin",
      locationName: "PulseLab 浦东店",
      goalLabel: "增肌与卧推表现提升",
      trainingLevel: "进阶",
      planVersion: 4,
      latestReviewRisk: "high",
      updatedAt: now,
    },
    {
      id: "member-lin",
      memberName: "林诗语",
      coachName: "教练 李安",
      coachId: "coach-li",
      locationName: "PulseLab 徐汇店",
      goalLabel: "产后恢复基础训练",
      trainingLevel: "新手",
      planVersion: 1,
      latestReviewRisk: "watch",
      updatedAt: now,
    },
    {
      id: "member-guo",
      memberName: "郭子航",
      coachName: "教练 王洁",
      coachId: "coach-wang",
      locationName: "PulseLab 静安店",
      goalLabel: "篮球专项体能提升",
      trainingLevel: "高级",
      planVersion: 5,
      latestReviewRisk: "normal",
      updatedAt: now,
    },
    {
      id: "member-he",
      memberName: "何予安",
      coachName: "教练 林策",
      coachId: "coach-lin",
      locationName: "PulseLab 浦东店",
      goalLabel: "减脂与代谢提升",
      trainingLevel: "新手",
      planVersion: 2,
      latestReviewRisk: "watch",
      updatedAt: now,
    },
  ],
  reviews: [
    {
      id: "review-chen-1",
      memberId: "member-chen",
      memberName: "陈奕辰",
      coachName: "教练 李安",
      locationName: "PulseLab 徐汇店",
      completedSessions: 3,
      totalSessions: 4,
      fatigueScore: 6,
      weightChangeKg: -0.6,
      note: "Day 4 因出差未完成，右膝偶尔不适。",
      riskLevel: "watch",
      nextAdjustment: "下肢训练采用更稳妥的动作替代，避免风险累积。",
      createdAt: now,
    },
    {
      id: "review-song-1",
      memberId: "member-song",
      memberName: "宋一帆",
      coachName: "教练 林策",
      locationName: "PulseLab 浦东店",
      completedSessions: 2,
      totalSessions: 4,
      fatigueScore: 8,
      weightChangeKg: 0.2,
      note: "卧推后肩前侧不适，睡眠偏差。",
      riskLevel: "high",
      nextAdjustment: "降低上肢推动作刺激并安排线下动作检查。",
      createdAt: "2026-04-16T08:00:00.000Z",
    },
    {
      id: "review-zhou-1",
      memberId: "member-zhou",
      memberName: "周可心",
      coachName: "教练 王洁",
      locationName: "PulseLab 静安店",
      completedSessions: 4,
      totalSessions: 4,
      fatigueScore: 4,
      weightChangeKg: -0.3,
      note: "完成度稳定，动作熟练度提升。",
      riskLevel: "normal",
      nextAdjustment: "下周可小幅提升训练密度。",
      createdAt: "2026-04-15T10:00:00.000Z",
    },
  ],
  appliedAssistantOutputs: {
    plan: null,
    guidance: null,
    review: null,
  },
};

export const demoAccounts = [
  { username: "member_chen", password: "123456", role: "member", label: "会员账号：陈奕辰" },
  { username: "member_zhou", password: "123456", role: "member", label: "会员账号：周可心" },
  { username: "coach_li", password: "123456", role: "coach", label: "教练账号：李安" },
  { username: "admin_root", password: "123456", role: "admin", label: "管理员账号：总部运营" },
] as const;

export const memberJourney = [
  { step: "01", title: "采集画像", description: "会员录入目标、训练频次、伤病史与器械条件。" },
  { step: "02", title: "AI 生成初稿", description: "系统输出结构化周计划与日训练卡片。" },
  { step: "03", title: "教练复核编辑", description: "教练可以直接改计划，但必须写入会员可见的修改理由。" },
  { step: "04", title: "执行与指导", description: "动作指导强制走检索与引用，高风险问题按严格保守边界处理。" },
  { step: "05", title: "复盘迭代", description: "根据完成率、疲劳与趋势更新下周计划，并同步给教练。" },
];

export const nutritionHints = [
  { title: "蛋白质优先", body: "每餐优先保证手掌大小的优质蛋白来源，训练后 1-2 小时内补充主食与蛋白质。" },
  { title: "碳水控制不过低", body: "减脂阶段不建议极端低碳，训练日前后保留基础主食，避免恢复和表现明显下降。" },
  { title: "门店可落地", body: "饮食建议以执行便利为优先，先做轻量规则，不在第一版做复杂营养计算。" },
];

export const rolePermissions = [
  { role: "管理员", permissions: "配置模型、Prompt、知识库状态，查看全量会员与教练数据。" },
  { role: "教练", permissions: "查看本人会员、编辑 AI 计划、填写会员可见修改理由、跟进风险提醒。" },
];

export const guidanceBase = {
  exercise: "哑铃罗马尼亚硬拉",
  target: "腘绳肌 / 臀部 / 后链",
  rpe: "7",
  rest: "90 秒",
  cues: [
    "起始位双脚与髋同宽，肩胛轻收，哑铃贴近身体。",
    "下放时先向后推髋，再保持脊柱中立让哑铃沿大腿滑下。",
    "感受到腘绳肌张力后回到起始位，避免用下背猛拉。",
  ],
  warmup: "训练前先做 5 分钟低强度单车，再做髋关节铰链练习和臀桥激活。",
  cooldown: "训练后做腘绳肌轻度拉伸和呼吸放松，不需要强压疼痛位。",
  alternative: "如果下背控制不足，可先改用壶铃硬拉或史密斯罗马尼亚硬拉。",
  citations: [
    {
      title: "动作规范库 / 罗马尼亚硬拉",
      snippet: "保持脊柱中立与髋主导是后链动作的核心，哑铃路径应贴近腿部。",
      source: "KB-动作规范-014",
      bucket: "kb-motion",
    },
    {
      title: "安全注意事项 / 腰背不适边界",
      snippet: "出现锐痛、麻木、症状放射或持续加重时，应停止训练并转专业评估。",
      source: "KB-安全边界-003",
      bucket: "kb-safety",
    },
    {
      title: "营养常识 / 训练日前后补给",
      snippet: "减脂阶段不建议极端低碳，训练日前后保留基础主食更利于恢复。",
      source: "KB-营养常识-002",
      bucket: "kb-nutrition",
    },
  ],
};

export const guidanceSignals = [
  {
    id: "normal",
    label: "正常动作询问",
    risks: [
      "在无疼痛和眩晕的前提下，按计划重量从 RPE 6-7 起步。",
      "如动作控制不稳，可先减重并缩短活动幅度。",
    ],
  },
  {
    id: "knee-pain",
    label: "训练时膝盖不适",
    risks: [
      "出现疼痛时不应继续按原计划加量，优先停止刺激并通知教练。",
      "系统不提供诊断与康复治疗建议，应由教练复核后决定是否转专业评估。",
    ],
  },
  {
    id: "dizzy",
    label: "训练后头晕",
    risks: [
      "头晕、胸闷、恶心等异常信号出现时，应立即停止训练并观察恢复情况。",
      "如果症状反复或加重，不应继续当日训练，应尽快寻求专业帮助。",
    ],
  },
];

export const guidanceLibrary = [
  {
    slug: "dumbbell-rdl",
    emoji: "🏋️",
    exercise: "哑铃罗马尼亚硬拉",
    target: "后链 / 臀腿",
    focus: "髋主导与脊柱中立",
    difficulty: "进阶",
    coachNote: "先稳定髋主导，再考虑加重。",
    sourceLabel: "知识库预置",
    summary: "适合提升后链发力与髋铰链控制，训练时优先关注路径贴腿和下放节奏。",
    order: ["低强度单车 5 分钟", "髋铰链练习 2 组", "主训练 3-4 组", "腘绳肌轻拉伸 + 呼吸恢复"],
    cues: [
      "双脚与髋同宽，肩胛轻收，哑铃贴近身体。",
      "下放时先向后推髋，再保持躯干稳定。",
      "回程时脚掌稳压地面，避免用下背猛拉。",
    ],
    warnings: [
      "出现锐痛、麻木或症状放射时应立即停止。",
      "下背控制不足时先减重或改用更稳的替代动作。",
    ],
  },
  {
    slug: "goblet-squat",
    emoji: "🦵",
    exercise: "高杯深蹲",
    target: "腿部 / 核心",
    focus: "下蹲路径与躯干稳定",
    difficulty: "新手友好",
    coachNote: "先把下蹲深度和膝盖轨迹做稳。",
    sourceLabel: "知识库预置",
    summary: "适合作为腿部基础动作，帮助建立蹲的节奏、深度和核心支撑。",
    order: ["踝髋热身 4 分钟", "体重深蹲 2 组", "高杯深蹲 3-4 组", "臀桥或呼吸放松"],
    cues: [
      "抱铃靠近胸前，保持肘部自然下垂。",
      "下蹲时脚掌均匀发力，膝盖方向跟随脚尖。",
      "起身时先稳住核心，再推地站起。",
    ],
    warnings: [
      "膝前疼痛明显时应缩短动作幅度并告知教练。",
      "如果跟腱或踝受限明显，优先做热身和高度调整。",
    ],
  },
  {
    slug: "incline-dumbbell-press",
    emoji: "💪",
    exercise: "上斜哑铃卧推",
    target: "胸肩前束 / 上肢推",
    focus: "肩胛稳定与推举轨迹",
    difficulty: "进阶",
    coachNote: "肩前侧有压迫感时，先减重并缩短幅度。",
    sourceLabel: "知识库预置",
    summary: "用于上肢推动作强化，重点是肩胛稳定、手腕叠线和下降控制。",
    order: ["弹力带肩部热身", "空手推举轨迹预演", "主训练 3-4 组", "胸肩轻放松"],
    cues: [
      "起始位肩胛微收，手腕保持正直。",
      "下放到上臂接近与地面平行即可，不必过度下压。",
      "推起时让哑铃略向中线靠拢，避免耸肩。",
    ],
    warnings: [
      "肩前侧刺痛或不稳定感明显时应停止该动作。",
      "疲劳末期轨迹漂移时优先结束该组，不强行追加次数。",
    ],
  },
  {
    slug: "split-squat",
    emoji: "⚖️",
    exercise: "分腿蹲",
    target: "单侧稳定 / 臀腿",
    focus: "骨盆控制与前脚发力",
    difficulty: "中级",
    coachNote: "速度宁慢，先把单侧控制做好。",
    sourceLabel: "知识库预置",
    summary: "适合提升单侧稳定与下肢控制，对跑跳基础和体态都很有帮助。",
    order: ["髋屈肌热身", "徒手分腿蹲 2 组", "持重训练 3 组", "股四头肌与臀部放松"],
    cues: [
      "前脚踩稳，骨盆保持正向。",
      "下放时后膝自然向下，不急着追求深度。",
      "起身时前脚发力，避免身体前冲。",
    ],
    warnings: [
      "膝盖不适时减少动作幅度并降低负荷。",
      "平衡明显不足时先扶固定物训练。",
    ],
  },
] as const;
